# Generated by Django 5.0.6 on 2024-09-16 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='count',
        ),
    ]
