# Generated by Django 5.0.6 on 2024-09-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
