# Generated by Django 5.1.2 on 2024-10-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_notification_read_remove_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liked_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
