# Generated by Django 5.1.2 on 2024-10-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_liked_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='liked_by_user',
        ),
    ]
